import type { BasketInstall } from "@/lib/installTemplates";
import type { PaletteProduct } from "../QuoteBuilderTab";
import { computeLineTotal, resolvePricingUnit } from "@/lib/pricingUnits";
// pricing is now simplified — cost_price is the source of truth

export interface QuoteArea {
  id: string;
  name: string;
  acUnits: AreaACUnit[];
  materials: AreaMaterial[];
  brackets: AreaBracket[];
  consumables: AreaConsumable[];
  timeHours: number;
  subtotal: number;
  appliedBundleId?: string;
}

export interface AreaACUnit {
  id: string;
  /** Hydrated from a saved quote line (its install lines already exist). */
  fromSaved?: boolean;
  product: PaletteProduct;
  btu: number;
  quantity: number;
}

export interface AreaMaterial {
  id: string;
  /** Standard-install link (kept through wizard re-saves). */
  install?: BasketInstall;
  product: PaletteProduct;
  defaultLength: number;
  adjustedLength: number;
  costPerMeter: number;
  totalCost: number;
  /** "length" = sold per metre with slider, "unit" = sold per quantity */
  pricingMode: "length" | "unit";
  /** quantity when in "unit" mode */
  unitQuantity: number;
  /** true when the line was generated by applying an installation bundle */
  fromBundle?: boolean;
  /** id of the bundle that generated this line */
  bundleId?: string;
  /** Present when this line IS a collapsed installation kit (see kitLine.ts). */
  kit?: AreaKitInfo;
}

export interface AreaKitInfo {
  name: string;
  pricingType: "p/meter" | "p/qty";
  /** Selling price ex VAT per metre (p/meter) or per kit (p/qty) */
  unitSell: number;
  unitCost: number;
  items: Array<{ name: string; code: string | null; quantity: number; isLengthItem: boolean }>;
}

export interface AreaBracket {
  id: string;
  size: string; // "450mm" | "650mm" | "L-shape"
  quantity: number;
  price: number;
}

export interface AreaConsumable {
  id: string;
  install?: BasketInstall;
  product: PaletteProduct;
  quantity: number;
  /** Whether this was auto-added from suggested_consumables */
  isSuggested?: boolean;
  /** true when the line was generated by applying an installation bundle */
  fromBundle?: boolean;
  /** id of the bundle that generated this line */
  bundleId?: string;
}


export function getBracketSize(btu: number): string {
  if (btu <= 18000) return "450mm";
  if (btu <= 24000) return "650mm";
  return "L-shape";
}

export function detectBTU(product: PaletteProduct): number {
  const text = [product.short_name, product.description, product.product_code].join(" ");
  const match = text.match(/(\d{4,5})\s*(?:btu|BTU)/i);
  if (match) return parseInt(match[1], 10);
  // common BTU values from model numbers
  const btuMap: Record<string, number> = {
    "9": 9000, "12": 12000, "18": 18000, "24": 24000, "36": 36000, "48": 48000,
  };
  const codeMatch = text.match(/(?:^|\D)(9|12|18|24|36|48)(?:\D|$)/);
  if (codeMatch && btuMap[codeMatch[1]]) return btuMap[codeMatch[1]];
  return 12000; // fallback
}

export function createEmptyArea(name: string): QuoteArea {
  return {
    id: crypto.randomUUID(),
    name,
    acUnits: [],
    materials: [],
    brackets: [],
    consumables: [],
    timeHours: 2,
    subtotal: 0,
  };
}

export function computeAreaSubtotal(area: QuoteArea): number {
  /** cost_price is the source of truth — already excl VAT, after any discount */
  const getCost = (p: any) => {
    if (p?.cost_price > 0) return p.cost_price;
    if (p?.cost_excl_vat > 0) return p.cost_excl_vat;
    return p?.selling_price || p?.price_per_metre || 0;
  };
  const acCost = area.acUnits.reduce((s, u) => s + computeLineTotal(u.quantity, getCost(u.product), resolvePricingUnit(u.product)), 0);
  const matCost = area.materials.reduce((s, m) => {
    if (m.kit) return s + m.kit.unitSell * (m.pricingMode === "length" ? m.adjustedLength : m.unitQuantity);
    if (m.pricingMode === "unit") {
      return s + computeLineTotal(m.unitQuantity, getCost(m.product), resolvePricingUnit(m.product));
    }
    const perM = m.costPerMeter || getCost(m.product);
    return s + (m.totalCost || perM * m.adjustedLength);
  }, 0);
  const bracketCost = area.brackets.reduce((s, b) => s + b.price * b.quantity, 0);
  const consCost = area.consumables.reduce((s, c) => s + computeLineTotal(c.quantity, getCost(c.product), resolvePricingUnit(c.product)), 0);

  return acCost + matCost + bracketCost + consCost;
}

export const WIZARD_STEPS = [
  { label: "Areas", description: "Define rooms" },
  { label: "AC Units", description: "Select units" },
  { label: "Pricing", description: "Markup & totals" },
  { label: "Time", description: "Labour hours" },
  { label: "Review", description: "Summary" },
] as const;
