ALTER TABLE leads ADD COLUMN IF NOT EXISTS assignment_method TEXT DEFAULT 'manual';
ALTER TABLE leads ADD COLUMN IF NOT EXISTS assignment_score DOUBLE PRECISION;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS broadcast_radius_km DOUBLE PRECISION DEFAULT 30;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS offer_count INTEGER DEFAULT 0;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS accepted_at TIMESTAMPTZ;