ALTER TABLE profiles ADD COLUMN IF NOT EXISTS workshop_address TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS workshop_lat DOUBLE PRECISION;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS workshop_lng DOUBLE PRECISION;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS home_lat DOUBLE PRECISION;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS home_lng DOUBLE PRECISION;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS home_radius_m INTEGER DEFAULT 500;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS max_travel_km DOUBLE PRECISION DEFAULT 50;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS skills TEXT[] DEFAULT '{}'::TEXT[];